[licenses]

allow = [ 
	"MIT" ,
	"Apache-2.0" ,
	"BSD-2-Clause" ,
	"BSD-3-Clause" ,
	"ISC" ,
	"MPL-2.0" ,
	"Unicode-DFS-2016" ,
	"OpenSSL" ,
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]